baseURL = "https://lgqm.halu.lu/"
languageCode = "zh"
defaultContentLanguage = "zh-cn"
title = "临高启明"
theme = "learn"

[params]
  author = "元老院"
  description = "临高启明小说阅读，git共享编辑。"
  disableSearch = true
  showVisitedLinks = true
  themeVariant = "blue"

[[menu.shortcuts]] 
  name = "<i class='fab fa-github'></i> Github"
  url = "https://github.com/lzjluzijie/lgqm"
  weight = 10

[[menu.shortcuts]] 
  name = "<i class='fab fa-telegram'></i> 讨论群"
  url = "https://t.me/lingaoqiming"
  weight = 20
