baseURL = "https://lgqm.halu.lu/"
languageCode = "zh"
defaultContentLanguage = "zh-cn"
title = "临高启明公开图书馆"
theme = "lgqm"
hasCJKLanguage = true
enableGitInfo = true

[params]
  gitRepo = "https://gitee.com/halulu/lgqm"
  editURL = "https://gitee.com/halulu/lgqm/edit/master/hugo/content/"
