version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.4
    working_directory: ~/blog
    steps:
      - add_ssh_keys:
          fingerprints:
            - "cb:80:d9:b2:c8:cc:df:89:b3:e3:dc:55:db:27:89:a9"
      - checkout
      - run: bash deploy.sh

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: master