version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: ~/lgqm
    steps:
      - add_ssh_keys:
          fingerprints:
            - "dd:49:52:fb:19:d0:e4:41:fd:70:e0:c0:fc:60:7a:89"
      - checkout
      - run: bash hugo/deploy.sh

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: master